// src/routes/about/+page.svelte
<script>
    import MetaTags from "$lib/components/MetaTags.svelte";
    import Icon from "@iconify/svelte";
    const references = [
        {
            name: "Beater's Guide",
            link: "https://docs.google.com/document/d/1zLKK_ZkcXPyNR3yLarz1r2LOjcwi200vLeBDwXIFBF0/edit",
        },
        {
            name: "H1G",
            link: "https://h1g.jp/blue-protocol/",
        },
        {
            name: "Info Database",
            link: "https://blue-protocol.info",
        },
        {
            name: "Ranpon",
            link: "https://burupuro-kouryaku.com/",
        },
        {
            name: "Bonyou",
            link: "https://bonyou.info/blue-protocol/",
        },
        {
            name: "Kanbatch",
            link: "https://baskmedia.jp/blue-protocol/",
        },
        {
            name: "Asterleeds.com",
            link: "https://asterleeds.com/maps",
        },
        {
            name: "The Luno",
            link: "https://www.the-luno.com/blue-protocol/",
        },
        {
            name: "Tokka",
            link: "https://gamebattleroyal.com/blue-protocol-zokusei/",
        },
        {
            name: "MSFL",
            link: "https://msfl.tokyo/blue-protocol-imagine#toc3",
        },
        {
            name: "JP Wiki",
            link: "https://blueprotocol.swiki.jp/",
        },
        {
            name: "Panke",
            link: "https://pankeynote.com/category/game/blue-protocol"
        },
        {
            name: "Protocol.blue",
            link: "https://protocol.blue/nt_enemies"
        }
    ];

    // TODO responsive about page
    let playAnimation = true;
</script>

<MetaTags title={`About — Bapharia`} description={`About Bapharia. Site credits and links to referenced material.`} />

<h1>About</h1>

<section class="centered-section">
	<div>
		<h2>Credits</h2>
		<p>Special thanks to everyone who contributed to this project.</p>
		<p class="special-thanks">
			Tan, Santa, Maru, Sigmy, tiny, Rhy, Kazarune, owl, SaintMorning,
			Ando, marko, Voldy, IncinerateZ
		</p>
	</div>
	<hr />
	<div class="grid g-50">
		<h3 style:font-size="var(--step-1)">Referenced Material</h3>
		<ul class="unstyled-list flex g-50">
			{#each references as reference}
				<li>
					<a
						class="btn btn-fadein"
						style="font-size: var(--step--1); padding: 0.5rem 1rem;"
						href={reference.link}
						rel="noopener nofollow noreferrer"
						target="_blank">{reference.name}</a
					>
				</li>
			{/each}
		</ul>
	</div>
	<hr />
	<p style:color="var(--text2)">
		BLUE PROTOCOL is a trademark of BANDAI NAMCO ONLINE INC. & BANDAI NAMCO
		STUDIOS INC.
	</p>
</section>

<!-- Discord membership, Discord nitro, Youtube membership, Youtube super thanks etc. -->

<style lang="scss">
    .special-thanks {
		// text-transform: uppercase;
		font-size: var(--step-0);
		color: var(--text2);
	}

	ul.unstyled-list {
		margin: auto;
		justify-content: center;
		max-inline-size: 70ch;
		flex-wrap: wrap;
	}
</style>

// src/components/About.tsx
import React from "react";
import './about.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

// About component
function About(props) {
    
    return (
        <>
            <div id="page-about-backdrop"></div>
            <article id="page-about show">
                <section>
                    <h3>Blue Protocol Fansite</h3>
                    Created by Zakum#3080
                </section>

                <section>
                    <h3>Special Thanks</h3>
                    tan, santa, maru, sigmy, tiny, rhy, kazarune, masi, niko, 0wl <br /><br />

                    <h3>Translations</h3>
                    Rubens "Ryuno" Moreira (pt br), Sniper Mask (ru), vadimhalo (ru) <br /><br />

                    <h3>Game assets are property of</h3>
                    © bandai namco online inc. <br />
                    © bandai namco studios inc. <br /><br />

                    <h3>References</h3>
                    <a href="https://docs.google.com/document/d/1zLKK_ZkcXPyNR3yLarz1r2LOjcwi200vLeBDwXIFBF0/edit" target="_blank" rel="noopener noreferrer nofollow">beater's guide</a>
                    <a href="https://h1g.jp/blue-protocol/" target="_blank" rel="noopener noreferrer nofollow">h1g</a>
                    <a href="https://blue-protocol.info" target="_blank" rel="noopener noreferrer nofollow">info database</a>
                    <a href="https://burupuro-kouryaku.com/" target="_blank" rel="noopener noreferrer nofollow">ranpon</a>
                    <a href="https://bonyou.info/blue-protocol/" target="_blank" rel="noopener noreferrer nofollow">bonyou</a>
                    <a href="https://baskmedia.jp/blue-protocol/" target="_blank" rel="noopener noreferrer nofollow">kanbatch</a>
                    <a href="https://asterleeds.com/maps" target="_blank" rel="noopener noreferrer nofollow">asterleeds</a>
                    <a href="https://www.the-luno.com/blue-protocol/" target="_blank" rel="noopener noreferrer nofollow">the luno</a>
                    <a href="https://gamebattleroyal.com/blue-protocol-zokusei/" target="_blank" rel="noopener noreferrer nofollow">tokka</a>
                    <a href="https://msfl.tokyo/blue-protocol-imagine#toc3" target="_blank" rel="noopener noreferrer nofollow">msfl</a>
                    <a href="https://blueprotocol-db.com/" target="_blank" rel="noopener noreferrer nofollow">jp database</a>
                    <a href="https://blueprotocol.swiki.jp/" target="_blank" rel="noopener noreferrer nofollow">jp wiki</a>
                    <a href="#">0wl's data</a>
                    <br /><br />

                    <h3>Community</h3>
                    <a className="icon" href="https://discord.gg/ZKwhn3a4yH" target="_blank" rel="noopener noreferrer nofollow">
                        <FontAwesomeIcon icon={["fab", "discord"]} />
                    </a>
                    <a className="icon" href="https://youtube.com/zakum" target="_blank" rel="noopener noreferrer nofollow">
                        <FontAwesomeIcon icon={["fab", "youtube"]} />
                    </a>
                    <a className="icon" href="https://twitter.com/hmyawp" target="_blank" rel="noopener noreferrer nofollow">
                        <FontAwesomeIcon icon={["fab", "twitter"]} />
                    </a>
                    <a className="icon" href="https://reddit.com/r/BlueProtocol" target="_blank" rel="noopener noreferrer nofollow">
                        <FontAwesomeIcon icon={["fab", "reddit-alien"]} />
                    </a>
                    <form action="https://www.paypal.com/donate" method="post" target="_blank">
                        <input type="hidden" name="hosted_button_id" value="JEYPMC4Z3QL3J" />
                        <input id="paypal-donation" type="submit" src="images/paypal.png" name="submit" title="Support the site via PayPal!" alt="Donate with PayPal button" />
                        <label htmlFor="paypal-donation" className="icon"><FontAwesomeIcon icon={["fab", "paypal"]} /></label>
                    </form>
                    <a className="icon" href="https://www.patreon.com/zakum" target="_blank" rel="noopener noreferrer nofollow">
                        <FontAwesomeIcon icon={["fab", "patreon"]} />
                    </a>
                </section>

                <section>
                    <h3>Enjoy some Blue Protocol Trivia!</h3>
                    <div id="trivia-wrapper">
                        <h4>Story</h4>
                        <h3>What is the name of the girl in charge of Adventurer Registration at the Frontiering Station?</h3>
                        <button>Divine Haven Hill</button>
                        <button>Soundless Foothills</button>
                        <button>Healing Boost Buff</button>
                        <button>Project Sky Blue</button>
                    </div>
                </section>
            </article>
        </>
    );

}

export default About;
